### ISSUE TITLE
column ordering issue

### ISSUE THREAD

**Issue by sanjayradadiya** [rodrigograca31/node-xls-to-json#1]
Hi Team,

When we pass Xls file with the following type of column ordering
```
_______________________
index | score | data
_______________________
  1   |   2   | test
_______________________
```

but the json is generated with following type of ordering

```
{
  data : "test",
  index : 1,
  score : 2
}
```
instead of

```
{
  index : 1,
  score : 2,
  data : "test"
}
```

**Comment by rodrigograca31** [comment]
🤔
Isnt that because JSON object properties are alphabetically ordered?
So, maybe nothing we can do? 🤔

**Comment by sanjayradadiya** [comment]
> 🤔
> Isnt that because JSON object properties are alphabetically ordered?
> So, maybe nothing we can do? 🤔

Yep, seems
